### ISSUE TITLE
Method code too large!

### ISSUE THREAD

**Issue by xiaowine** [CodingGay/BlackObfuscator-ASPlugin#31]
编码后运行直接闪退抛出错误Method code too large!
```
java.lang.RuntimeException: d2j fail translate: java.lang.RuntimeException: Method code too large!
                                                                                                    	at org.objectweb.asm2.MethodWriter.getSize(MethodWriter.java:2036)
                                                                                                    	at org.objectweb.asm2.AsmBridge.sizeOfMethodWriter(AsmBridge.java:31)
                                                                                                    	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:54)
                                                                                                    	at com.googlecode.d2j.dex.Dex2jar$2.convertCode(Dex2jar.java:134)
                                                                                                    	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:686)
                                                                                                    	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:476)
                                                                                                    	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:379)
                                                                                                    	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:515)
                                                                                                    	at com.googlecode.d2j.dex.Dex2jar.doTranslate(Dex2jar.java:190)
                                                                                                    	at com.googlecode.d2j.dex.Dex2jar.to(Dex2jar.java:295)
                                                                                                    	at com.googlecode.dex2jar.tools.Dex2jarCmd.doCommandLine(Dex2jarCmd.java:120)
                                                                                                    	at com.googlecode.dex2jar.tools.BaseCmd.doMain(BaseCmd.java:290)
                                                                                                    	at top.niunaijun.blackobfuscator.core.ObfDex.handleDex(ObfDex.java:99)
                                                                                                    	at top.niunaijun.blackobfuscator.core.ObfDex.obf(ObfDex.java:34)
                                                                                                    	at top.niunaijun.blackobfuscator.core.ObfDex$obf.call(Unknown Source)
                                                                                                    	at top.niunaijun.blackobfuscator.ObfPlugin$1$_execute_closure1.doCall(ObfPlugin.groovy:45)
                                                                                                    	at jdk.internal.reflect.GeneratedMethodAccessor739.invoke(Unknown Source)
                                                                                                    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                                    	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                                                                                                    	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
                                                                                                    	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
                                                                                                    	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
                                                                                                    	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
                                                                                                    	at groovy.lang.Closure.call(Closure.java:412)
                                                                                                    	at groovy.lang.Closure.call(Closure.java:428)
                                                                                                    	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2357)
                                                                                                    	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2342)
                                                                                                    	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2383)
                                                                                                    	at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source)
                                                                                                    	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:242)
                                                                                                    	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51)
                                                                                                    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
                                                                                                    	at top.niunaijun.blackobfuscator.ObfPlugin$1.execute(ObfPlugin.groovy:39)
                                                                                                    	at top.niunaijun.blackobfuscator.ObfPlugin$1.execute(ObfPlugin.groovy)
                                                                                                    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:835)
                                                                                                    	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:808)
                                                                                                    	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
                                                                                                    	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
                                                                                                    	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:233)
```

**Comment by xzzvsxd** [comment]
+1 代码块过长就会这样

**Comment by han023** [comment]
have you found any solution

**Comment by xzzvsxd** [comment]
Reduce the layers of code or string obfuscation and debug step by step—u’ll find a sweet spot where errors don’t pop up.

**Comment by han023** [comment]
By layer of code, you mean the depth of BlackObfuscator. If yes, I made the depth 0, but the same problem is coming.
